### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by gorgobacka** [partitioncloud/partitioncloud-server#3]
This seems to be a very interesting software. I tried it locally and it works well.
But it was a bit difficult to understand where I have to click.

Will there be an English version available in the future?

**Comment by augustin64** [comment]
Hi! I understand you had a hard time finding where to click if you don't speak french, the UX could be more intuitive.

To be fair, there wasn't any need to support different locals until now, but I will have a look into it and keep you up to date.

**Comment by augustin64** [comment]
Hi @gorgobacka, support for different languages has been added in #4.
Keep me updated if it stays as hard to understand where to click as before. (`README.md` is still in French though)

**Comment by gorgobacka** [comment]
Thanks a lot. I will check it in the coming days.

**Comment by gorgobacka** [comment]
I just tested it and it works great. Thanks for translating everything. It's also a good base for further languages.
